### ISSUE TITLE
🏅 Hooks: All About Render

### ISSUE THREAD

**Issue by thchia** [react-knowledgeable/talks#1]
Speaker Profile
---
My name is Thomas. I am a front end developer who loves React. My other interests include casual Minesweeper and listening to music in foreign languages I don’t understand.

Intro
---

When hooks were introduced in React, much ado was made about how they afforded a cleaner, more shareable way to manage state.

In this talk I focus on the _other_ consequence - rethinking a components lifecycle in functional components. I’ll explore what it means for things to “participate in the data flow” and how other built in hooks guide us towards this new way of thinking.

Planner
---
- I prefer to give this talk at: August/September?
- I'd like to schedule a prep discussion with one of the RK kids: Yes @wgao19

**Comment by wgao19** [comment]
Hey Thomas, great to have you on our first event!!

We need one more piece of information, how many minutes do you need to ⚡️？You have the options of 7, 8, 9, or 10 minutes.

Referencing #3

**Comment by thchia** [comment]
Because I am somewhat auspicious, I will go for 8 minutes ✌️

**Comment by wgao19** [comment]
Video
---
- [here](https://engineers.sg/video/hooks-all-about-render-react-knowledgeable--3589)

**Comment by wgao19** [comment]
hiiii @thchia please update your slides thanks :)))))

**Comment by thchia** [comment]
# Slides

[here](https://docs.google.com/presentation/d/1w5NT-j9JHIkagNyql2Y_3OdYrqYvqN-gChQ43qfB-Jk)

**Comment by wgao19** [comment]
Thank you!
