### ISSUE TITLE
⚛ React this month – Sept 2019

### ISSUE THREAD

**Issue by wgao19** [react-knowledgeable/talks#10]
Hi React people in this town, we're opening proposals to the opening React updates for our first event in Sept 5, #9 

How to participate
---
If you'd like to conduct this sharing, **reply this issue** and list your proposed items to share. You may keep editing your proposal. We'll pick a list that seems most interesting by Tuesday, Sept 3.

**Comment by wgao19** [comment]
⚛️ [React 16.9 is out](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html)
---
- more UNSAFE_ lifecycle methods
- deprecated unheardof stuff
- acync act() for testing
- Performance Measurements with <React.Profiler>
- need to wait longer for a combined release of concurrent mode + suspense for data 
fetching `¯\_(ツ)_/¯` i am not even surprised

🛠 [New DevTools](https://reactjs.org/blog/2019/08/15/new-react-devtools.html) (demo)
---
- [changelog](https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md#400-august-15-2019)
- [interactive tutorial](https://react-devtools-tutorial.now.sh/)

🥯 Flow v0.106 [Coming Soon: Changes to Object Spreads](https://medium.com/flow-type/coming-soon-changes-to-object-spreads-73204aef84e1)
---
- the current model is based on an assumption that inexact object types do not specify own-ness, this makes properties from spread become optional because object spread at run time copies only _own_ properties
- the new model assumes inexact object types specify own-ness on specified properties, therefore following our intuition of object spread more closely
- inexact objects _may_ contain more properties that may overwrite existing properties in spread target
- the new model will err, tell us what happens, and ask if we can make the spreaded object exact

**Comment by thchia** [comment]
React 16.9 same birthday as Singapore.

**Comment by wgao19** [comment]
thank you @thchia for delivering this together!
