### ISSUE TITLE
🦖 How Modern Static Site Generators Work

### ISSUE THREAD

**Issue by yangshun** [react-knowledgeable/talks#11]
## Speaker Profile

My name is Yangshun. I am a Front End Engineer at Facebook. I'm reachable on Twitter ([@yangshunz](https://twitter.com/yangshunz))

## Intro

I'd like to talk about the architecture of modern SSGs (static site generators) and how they work.

Jekyll, Hexo, and Hugo are few of the earliest static site generators to have been invented and they have been used to build a significant number of websites in history. More recently, modern SSGs such as Gatsby, Next, Docusaurus and VuePress have emerged. These SSGs are an improvement over traditional SSGs - the initial render is HTML but sequent navigations utilize HTML `pushState()` and client-side rendering. Such hybrid rendering approaches provide an awesome user experience of a fast initial load (low TTI) and fast subsequent navigations.

This talk goes into the inner mechanisms behind how modern SSGs are built and their architecture. *Spoiler alert - they're really similar!* We will also see how Docusaurus is an example of such a modern SSG framework that can be used for building fast and performant websites.

## Planner

- I prefer to give this talk at: September
- Number of minutes needed to ⚡️: 10

**Comment by wgao19** [comment]
Amazing! I'm so personally looking forward to this talk 💃 Thank you for speaking here!!

**Comment by wgao19** [comment]
Referencing #9

**Comment by yangshun** [comment]
Thanks for attending the talk! My slides can be found here for those who are interested:
[React Knowledgeable - How Modern Static Site Generators Work.pdf](https://github.com/react-knowledgeable/react-knowledgeable-talks/files/3584661/React.Knowledgeable.-.How.Modern.Static.Site.Generators.Work.pdf)

**Comment by wgao19** [comment]
thanks for speaking! your talk video will be posted over the weekend, will update once they're posted
