### ISSUE TITLE
💄 Build a Gatsby Theme and publish

### ISSUE THREAD

**Issue by email2vimalraj** [react-knowledgeable/talks#13]
speaker profile
---
My name is Vimalraj Selvam. I am a Staff Software Engineer at Visa Worldwide Pte Ltd. I build various visualisation tools using React for my company which is heavily used by the command center teams. I am mostly reachable via [twitter](https://twitter.com/email2vimalraj).

intro
---

I'd like to speak about **Build a Gatsby theme and publish**. Here's a little more background and motivation about the talk:

Gatsby is an open source framework based on React and GraphQL which lets developers to build fast websites. Very recently Gatsby announced theme support which makes the life even more easier because all our default configuration, design, share functionalities will be abstracted out from our side and can be used as an installable package. I'm going to show on how to build a simple gatsby theme quickly and publish to npm registry. Also, I'll be showing on how to use the package from the npm and build a quick simple website.

As you can see above, I have a point to make. Please let me in thanks.

planner
---
- I prefer to give this talk at: September
- Number of minutes needed to ⚡️: 10  🤔

**Comment by wgao19** [comment]
Great to have you and looking forward to hearing about Gatsby Themes!
Referencing September issue #9

**Comment by email2vimalraj** [comment]
Slide: https://github.com/email2vimalraj/gatsby-theme-like-post/blob/master/build-gatsby-theme-talk.key
Demo repo: https://github.com/email2vimalraj/gatsby-theme-like-post

**Comment by wgao19** [comment]
video: https://engineers.sg/v/3638

thank you :)
