### ISSUE TITLE
⚛ React this month – Oct 2019

### ISSUE THREAD

**Issue by wgao19** [react-knowledgeable/talks#17]
React updates tracker issue for Oct 2019, #12

**Comment by wgao19** [comment]
- DevTools 4.1, 4.2 released
  - Props/state editor supports ([#16612](https://github.com/facebook/react/pull/16700))
  - "Highlight updates" is back ([#16989](https://github.com/facebook/react/pull/16989))
- Flow [v0.107](https://github.com/facebook/flow/releases/tag/v0.107.0), [v0.108](https://github.com/facebook/flow/releases/tag/v0.108.0), [v0.109](https://github.com/facebook/flow/releases/tag/v0.109.0) released
- React 16.10 released
  - [changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md#16100-september-27-2019)
  - [intro heaps](https://www.cs.cmu.edu/~adamchik/15-121/lectures/Binary%20Heaps/heaps.html)
  - [PR that put this in](https://github.com/facebook/react/pull/16245)
  - [r/reddit](https://www.reddit.com/r/reactjs/comments/da672f/react_16100_is_out/?utm_source=share&utm_medium=web2x)

will update more details later

**Comment by JennieJi** [comment]
React router v5.1.x released, now we have more hooks: useParams, useLocation, useHistory, and useRouteMatch hooks : https://github.com/ReactTraining/react-router/releases
