### ISSUE TITLE
🔐 Gatsby w/ authentication... and hooks

### ISSUE THREAD

**Issue by omonk** [react-knowledgeable/talks#18]
who are you and where to find you
---
Ollie Monk - [twitter](https://twitter.com/ollie_monk)

intro of the talk
---

Gatsby can manage authentication pretty well, but how do we take it to the next level with everyone's favourite React API - Hooks! I'll be detailing how to integrate authentication with Swizec's awesome [`useAuth`](https://github.com/Swizec/useAuth) library.

planner
---
- I prefer to give this talk at: https://github.com/react-knowledgeable/react-knowledgeable-talks/issues/12
- Number of minutes needed to ⚡️:  9

**Comment by wgao19** [comment]
Hi @omonk do you have slides to share?
