### ISSUE TITLE
🤖 Let bot refactor the code

### ISSUE THREAD

**Issue by email2vimalraj** [react-knowledgeable/talks#19]
who are you and where to find you
---
My name is Vimalraj Selvam. I am a Staff Software Engineer at Visa Worldwide Pte Ltd. I build various visualisation tools using React for my company which is heavily used by the command center teams. I am mostly reachable via [twitter](https://twitter.com/email2vimalraj).

intro of the talk
---

With evolving changes in the Javascript ecosystem, the libraries tend to break things often when new versions introduced. Often, we spend lot of time to fix the breaking changes in a large codebase by refactoring manually (maybe through search and replace 🤷🏻‍♂️). But, with ASTs, babel, jscodeshift we can make refactoring automated (for example, heard about react-codemod). I'll start with talking under the hood of react-codemod and then will show case few usecases and examples how we can leverage the tools to create our refactoring bot 🤖.

planner
---
- I prefer to give this talk at: https://github.com/react-knowledgeable/react-knowledgeable-talks/issues/12
- Number of minutes needed to ⚡️: 10

**Comment by wgao19** [comment]
great :) looking forward 👩🏻‍🌾

**Comment by wgao19** [comment]
Thank you @email2vimalraj for the talk, it was so cool! I'll likely be building something related in the near future and would definitely love to look into your repo (after you make it public, and no hurries). And maybe discuss about that too :)

**Comment by wgao19** [comment]
closing since it’s past :)
