### ISSUE TITLE
👞 Dancing with React Hooks

### ISSUE THREAD

**Issue by SmokinClove** [react-knowledgeable/talks#2]
speaker profile
---
My name is Van. I am a front end developer at Shopee Singapore. In no particular order i like music, coffee, cats, books, black color, Hosoya Yoshimasa.

intro
---

React Hooks is THE hot thing now. More and more people can teach you how to use React Hooks, how they work, what the rules are and why.

What did you first use React Hooks to make? For me, it was to let someone dance.

Join me in your black suit and dress as i introduce to you my Tiny Dancer, and how Hooks made me revisit an important concept in Javascript.

planner
---
- I prefer to give this talk at: end of August or September
- Number of minutes needed to ⚡️: 10

resources
---
- [slides](https://docs.google.com/presentation/d/1mrGSHBNYoUlMYrOWZ6BMiJ4rCvfJqIq1XgTuPkePkkM/edit?usp=sharing)
- [video](https://engineers.sg/video/dancing-with-react-hooks-react-knowledgeable--3637)

**Comment by SmokinClove** [comment]
Slides here https://docs.google.com/presentation/d/1mrGSHBNYoUlMYrOWZ6BMiJ4rCvfJqIq1XgTuPkePkkM/edit?usp=sharing
Thanks for being there folks!

**Comment by wgao19** [comment]
thank you for the amazing talk!
