### ISSUE TITLE
⚡️ Incredible usage of GraphQL's schema ✡️

### ISSUE THREAD

**Issue by nutstick** [react-knowledgeable/talks#22]
who are you and where to find you
---
My name is Nuttapat Kirawittaya. I'm a react-native developer at Shopee. I love GraphQL.

intro to the talk
---

GraphQL is a query language for your API. There are a lot of benefits gained if you using it. For my point of view, the best benefit of GraphQL is not that we can reduce number of requests or prevent overfetching. The best feature of GraphQL is schema which allows developers, tools to work together seamlessly. I will show my usage of schema including Apollo plugin for your vscode, Type generate from your schema, automatic reviewing schema changes using GraphQL Inspector

---

planner
---
- I prefer to give this talk at: #12 
- Number of minutes needed to ⚡️: 10

**Comment by wgao19** [comment]
moved to #20

**Comment by yishus** [comment]
cool @nutstick would you be ready to speak at #20? And we'll need your help to expand on your talk's description, plus the number of minutes you would need for the talk

**Comment by nutstick** [comment]
Okay sure.

**Comment by wgao19** [comment]
Resources
---
- **video**  
  https://engineers.sg/video/incredible-usage-of-graphql-s-schema-react-knowledgeable--3756

**Comment by wgao19** [comment]
Hey @nutstick, thanks for the talk! Hope to hear from you again :)
