### ISSUE TITLE
⛰ Heaps: Magic

### ISSUE THREAD

**Issue by thchia** [react-knowledgeable/talks#23]
who are you and where to find you
---
I am Thomas, annoyer of meetup attendees. You can find me on Twitter at @th___chia ... and at meetups. 

intro of the talk
---

React 16.10 featured a move from using an array to a binary heap in the implementation of a priority queue. I briefly look at why this was done and show the magic of binary heaps (hint: there will be a bit of maths, like really tiny bit). 

planner
---
- I prefer to give this talk at: #12 
- Number of minutes needed to ⚡️: 111 (answer given in binary) 

slides
---
[Here](https://docs.google.com/presentation/d/1ui2gwIf7DWz7sBUtFG2SIwmCsk4WI4Dj8yzC9jL1o-w/edit?usp=sharing)

video
---
[Here](https://engineers.sg/v/3710)

**Comment by wgao19** [comment]
Thank you, bravo!
