### ISSUE TITLE
🧞‍♂️ Supercharge redux with Immer.js

### ISSUE THREAD

**Issue by phamtm** [react-knowledgeable/talks#25]
who are you and where to find you
---
My name is Minh Pham. I am an enterprise engineer from Facebook. Most of the stuffs I built are internal apps that helps with the logistic side of our business. I am a full stack developer but not long ago I spent all of my time in React land.

intro of the talk
---
Making the state of your react apps immutable has several upsides (easier to optimize rendering with `shouldComponentUpdate` for eg). `Immutable.js` (by Facebook) was the first stab at the problem. However there are a few problems: 
- lack of strict typing
- awkward apis

`Immer.js` one of the few library that has done it right, even earning the high praise of React maintainer https://twitter.com/sebmarkbage/status/1032684851063705600
In this talk, I plan to explain how using `immer.js` can leads to better code and increase your productivity in a typical React app.

Slide
https://drive.google.com/open?id=1tNbU6ftcpwMwQQMAQ6X7-wwYImvbTlsvgez4nCsHk78

planner
---
- I prefer to give this talk at: #20 
- Number of minutes needed to ⚡️:  10

**Comment by wgao19** [comment]
cooooool, looking forward

high praise from sebastian ah, looking forward +1

**Comment by yishus** [comment]
thanks for submitting @phamtm! looking forward to it :)

**Comment by wgao19** [comment]
Hey @phamtm do you mind putting a link to your slides?

Resources
---
- **video** by the world classly @engineersftw  
  https://engineers.sg/video/supercharge-redux-with-immer-js-react-knowledgeable--3758

**Comment by phamtm** [comment]
I updated the slide in the proposal

**Comment by wgao19** [comment]
cool, thanks again!
