### ISSUE TITLE
⚛ React this month – Nov 2019

### ISSUE THREAD

**Issue by wgao19** [react-knowledgeable/talks#26]
React updates tracker issue for Nov 2019, #20. Assigning to @yishus cuz she said she'll take it :]

**Comment by yishus** [comment]
- [React Prereleases](https://reactjs.org/blog/2019/10/22/react-release-channels.html)
- Relay [v7.0.0](https://github.com/facebook/relay/releases/tag/v7.0.0)
- Concurrent Mode [docs](https://reactjs.org/docs/concurrent-mode-intro.html)
  - [Integration with Relay](https://relay.dev/docs/en/experimental/a-guided-tour-of-relay#loading-states-with-suspense)
- react-beautiful-dnd [v12.0.0](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v12.0.0)
- Formik [v2.0.1](https://github.com/jaredpalmer/formik/releases/tag/v2.0.1), v2.0.2, v2.0.3
  - [v2 tutorial PR](https://github.com/jaredpalmer/formik/pull/1831)

**Comment by yishus** [comment]
Interesting reads
- [19 Takeaways From React Conf 2019](https://blog.anthonymorris.dev/19-takeaways-from-react-conf-2019)
- [Portals with Context](https://reacttraining.com/blog/portals-with-context/)
- [Immutable JavaScript Data Structures with Immer](https://egghead.io/courses/immutable-javascript-data-structures-with-immer)

Tools
- [Reakit](https://reakit.io)

**Comment by wgao19** [comment]
hi @yishus would u like to PR the site so that the content will show up on the slides?

speaking of this, maybe eventually we’ll fetch this content from GH issue directly

**Comment by yishus** [comment]
oh yea i'm using this space as draft before PR-ing to the site :)
