### ISSUE TITLE
📱 Nuances of React Native

### ISSUE THREAD

**Issue by KenLSM** [react-knowledgeable/talks#27]
who are you and where to find you
---
Hey, this is Ken here. I am a react-native developer from Shopee.

intro of the talk
---

Having not delivered production code in React Native previously before joining my current company, there were many times things were different in React Native and React. In this short pointed bullet points, I will quickly run through nuances of React Native when setting foot from React.

media
---
- [slides](https://slides.com/kenlee-4/nuances-react-native)
- [video](https://engineers.sg/video/nuances-of-react-native-react-knowledgeable--3757)

planner
---
- I prefer to give this talk at: #20 
- Number of minutes needed to ⚡️:  7

**Comment by wgao19** [comment]
cool :)

**Comment by wgao19** [comment]
Hey @KenLSM could you please add link to your slides?

- **video** by the world classly @engineersftw  
  https://engineers.sg/video/nuances-of-react-native-react-knowledgeable--3757
