### ISSUE TITLE
🧪 Gaining Confidence in React App through Testing

### ISSUE THREAD

**Issue by zainfathoni** [react-knowledgeable/talks#28]
who are you and where to find you
---
I'm [Zain Fathoni](https://www.zainfathoni.com), a Senior Software Engineer at [Ninja Van](https://www.ninjavan.co).
You can reach me through [Telegram](https://t.me/zainfathoni) or [Twitter](https://twitter.com/zainfathoni).

intro of the talk
---

Have you ever felt that writing tests are merely a ritual to increase the code coverage without gaining any significant value from them? Do you think that your tests don't make you confident enough with your codes?

Let's hear what I've got to say about them! Whether you're an experienced developer in testing or never write any test code, I believe you would gain something from this talk.

planner
---
- I prefer to give this talk at: #20 
- Number of minutes needed to ⚡️: 10
- Slideshow preview: ~~[This slide](https://confident-react-testing.netlify.com/) might be too long for a 10-minute talk. I used it when I was speaking at [a meetup in Indonesia](https://www.zainfathoni.com/talk/reactjs-id-meetup-1). I can cut them down to fit the 10 minutes slot provided.~~
  I updated the slide, and you can open it over here: https://confident-react-testing.netlify.com/

**Comment by wgao19** [comment]
Hi @zainfathoni , thank you for bringing this talk to RK! 
Got one comment and one question --
- regarding time slot, please do try to fit this into 10 mins ⚡️ we love & share the spirits of lightning talk a lot please give it a try
- regarding topic and which event to deliver this, our upcoming event #20 is actually open for one more talk, i'm wondering if you can make it to next Thursday, nov 7? if not, dec 5 is also ok! (jamstack sites also need testing watttt)

**Comment by zainfathoni** [comment]
Hi @wgao19 ,

- Sure, I will try to squeeze the slides and send you another preview soon.
- I was not aware of that. I thought the upcoming event slot is full already. 😅
  I want to present this as soon as possible. So yes, I can make it to next Thursday, Nov 7.
  I just updated the issue description to the #20 event. Thanks!

**Comment by wgao19** [comment]
Cool, looking forward to your talk @zainfathoni!

**Comment by wgao19** [comment]
Hi @zainfathoni , thanks for the talk! By the way, a lot of people are asking about the code presenting library that you're using. Could you please put up a link to that as well?

**Comment by wgao19** [comment]
resources
---
- **video** by the world classly @engineersftw  
  https://engineers.sg/video/gaining-confidence-in-react-app-through-testing-react-knowledgeable--3755
- **slides**  
  https://confident-react-testing.netlify.com/

**Comment by zainfathoni** [comment]
# Resources

* **Talk Page** in my personal website
  https://zainfathoni.com/talk/react-knowledgeable-meetup-4
* **Slides Repository**
  https://github.com/zainfathoni/confident-react-testing
