### ISSUE TITLE
💸 (Ec)static Commerce

### ISSUE THREAD

**Issue by thorsten-stripe** [react-knowledgeable/talks#31]
speaker
---
Hello, I'm [Thor](https://twitter.com/thorwebdev) (雷神), a Developer Advocate at Stripe working with many different technologies on the web to grow the GDP of the internet. Having spent most of my time with Stripe users in Europe, I recently moved to Singapore to learn from and all about APAC's developer communities.

intro
---

In this hands-on ⚡️talk we'll explore how we can use Gatsby themes to spin up a simple storefront using [Stripe Checkout](https://stripe.com/payments/checkout), and we'll look behind the scenes of the [Gatsby Swag Store](https://store.gatsbyjs.org/) to see how we can take our static commerce page to the next level with the [Shopify GraphQL API](https://shopify.github.io/js-buy-sdk/).

resources
---
- video  
  https://engineers.sg/v/3828

<details>
  <summary>planner</summary>

- https://github.com/react-knowledgeable/events/issues/5
- Number of minutes needed to ⚡️: 10 
- [x] I am happy to have this talk recorded by @engineersftw (by default, we record talks to be accessible by more audience, if you don't want, please uncheck this)

</details>

**Comment by fajarsiddiqfs** [comment]
See you all!

**Comment by wgao19** [comment]
hi @thorsten-stripe thank you for the talk!
