### ISSUE TITLE
🌏 Navigating i18n in SEA with Gatsby

### ISSUE THREAD

**Issue by zainfathoni** [react-knowledgeable/talks#32]
who are you and where to find you
---
I'm [Zain Fathoni](https://www.zainfathoni.com), a Senior Software Engineer at [Ninja Van](https://www.ninjavan.co).
You can reach me through [Telegram](https://t.me/zainfathoni) or [Twitter](https://twitter.com/zainfathoni).

intro
---

[Ninja Van](https://www.ninjavan.co) has established its presence in six countries across South East Asia for the past few years.

Recently we revamped our website using [Gatsby](https://www.gatsbyjs.org/) to enable us to customize its components in React.
This talk is a story about my ups and downs in getting i18n works properly at our website to serve those countries in [two](https://www.ninjavan.co) [different](https://www.ninjaxpress.co) domains.

resources
---
- video  
  https://engineers.sg/v/3827
- slides
  https://i18n-gatsby.netlify.com/
- slides repository
  https://github.com/zainfathoni/i18n-gatsby
- blog post
  https://www.zainfathoni.com/talk/react-knowledgeable-meetup-5

<details>
  <summary>planner</summary>

- I prefer to give this talk at: react-knowledgeable/events#5 
- Number of minutes needed to ⚡️: 10
- [x] I am happy to have this talk recorded by @engineersftw (by default, we record talks to be accessible by more audience, if you don't want, please uncheck this)

</details>

**Comment by wgao19** [comment]
Ohhhh cool :) Looking forward!

**Comment by fajarsiddiqfs** [comment]
Can't wait for this! see you there!

**Comment by wgao19** [comment]
hey @zainfathoni thank you for the talk! could you please update slides / links in the resources section?

will close this issue now, feel free to update the content and it will be picked up by our website in the next release
