### ISSUE TITLE
👨🏻‍🔧👷🏻‍♂️ Writing a Gatsby plugin

### ISSUE THREAD

**Issue by tanhauhau** [react-knowledgeable/talks#34]
who are you and where to find you
---

intro
---

Why use plugin developed by others while you can write your own plugin 🤔

I will share a generic template/steps to write your own plugin, making your Gatsby site one of a kind 😎

resources
---
- video  
  https://engineers.sg/video/writing-a-gatsby-plugin--3829

<details>
  <summary>planner</summary>

- I prefer to give this talk at: react-knowledgeable/events#5 
- Number of minutes needed to ⚡️: 10 
- [x] I am happy to have this talk recorded by @engineersftw (by default, we record talks to be accessible by more audience, if you don't want, please uncheck this)

</details>

**Comment by wgao19** [comment]
hi @tanhauhau thank you for the talk, could you please help update slides / links in the resources section?
