### ISSUE TITLE
🔁 Quick Quicksort

### ISSUE THREAD

**Issue by thchia** [react-knowledgeable/talks#36]
who are you and where to find you
---
Thomas Chia. Find me in white t shirts. @th__chia and the author of... this issue. 

intro of the talk
---

Once I gave a talk on binary heaps and I enjoyed it (I’m not sure about the audience). I liked it so much I will tackle another topic: Quicksort. Come and learn how to divide and conquer in 10mins (or less). 

<details>
  <summary>planner</summary>

- I prefer to give this talk at: react-knowledgeable/events#6 
- Number of minutes needed to ⚡️: 10 
- [x] I am happy to have this talk recorded by @engineersftw (by default, we record talks to be accessible by more audience, if you don't want, please uncheck this)

</details>

**Comment by wgao19** [comment]
thank you for this talk :)
