### ISSUE TITLE
🌊 Adding Codewaves into gatsby blog

### ISSUE THREAD

**Issue by email2vimalraj** [react-knowledgeable/talks#38]
who are you and where to find you
---
My name is Vimalraj Selvam. I am a Staff Software Engineer at Visa Worldwide Pte Ltd. I build various visualisation tools using React for my company which is heavily used by the command center teams. I am mostly reachable via [twitter](https://twitter.com/email2vimalraj).

intro
---

Recently Mr. [Rodrigo Pombo](https://github.com/pomber) had published a post on his blog on [Building our own React](https://pomb.us/build-your-own-react/) which caught many eyes especially in terms of how he presented the post to audience. All this made possible by his own Gatsby based theme called [Gatsby Waves](https://github.com/pomber/gatsby-waves). During this talk I'll show on how we can use this theme in our blog and make our blog more prettier.

resources
---
- video  
  https://engineers.sg/video/adding-codewaves-into-gatsby-blog--3826

<details>
  <summary>planner</summary>

- I prefer to give this talk at: react-knowledgeable/events#5 
- Number of minutes needed to ⚡️: 10
- [x] I am happy to have this talk recorded by @engineersftw (by default, we record talks to be accessible by more audience, if you don't want, please uncheck this)

</details>

**Comment by wgao19** [comment]
Oh nice! 

On a personal note, will you talk about its internals? I'm really curious how it's built since it shares a similar take with my approach

**Comment by wgao19** [comment]
hey @email2vimalraj thank you for the talk! could you plz help update your slides / any resources in the resources section?
