### ISSUE TITLE
🔃 Tim Sort

### ISSUE THREAD

**Issue by tanhauhau** [react-knowledgeable/talks#40]
speaker
---

Tan Li Hau
Twitter: @lihautan

intro
---

Related to https://github.com/react-knowledgeable/talks/issues/36, let's look into another sorting algorithm, Timsort.

Java's [Arrays.sort](https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html#sort(java.lang.Object[])), Python's [list.sort](https://docs.python.org/3.3/howto/sorting.html?highlight=timsort#sorting-how-to), and recently [V8 Array.prototype.sort](https://v8.dev/features/stable-sort) uses this stable sorting algorithm. So, what is this sorting algorithm about?

resources
---

<details>
  <summary>planner</summary>

- I prefer to give this talk at: react-knowledgeable/events#6 
- Number of minutes needed to ⚡️: 8
- [x] I am happy to have this talk recorded by @engineersftw (by default, we record talks to be accessible by more audience, if you don't want, please uncheck this)

</details>

**Comment by wgao19** [comment]
thanks for this talk!
