### ISSUE TITLE
🌳 B-Trees

### ISSUE THREAD

**Issue by KenLSM** [react-knowledgeable/talks#41]
speaker
---

I'm Ken. I wear long pants and collared tees only when I am speaking or hosting.
Twitter: kenleesm

intro
---

Going along with the sorting algorithm theme, I will talk why B-Trees is developed and where it is used and which doesn't simply sorts an input but returns to you as a structured data. This tree is not commonly found in your daily usage.
If you are using B-Trees in your FE work, something is probably wrong.

resources
---

<details>
  <summary>planner</summary>

- I prefer to give this talk at: react-knowledgeable/events#6 
- Number of minutes needed to ⚡️: 
- [x] I am happy to have this talk recorded by @engineersftw (by default, we record talks to be accessible by more audience, if you don't want, please uncheck this)

</details>

**Comment by wgao19** [comment]
omg great algo party in the jan event

**Comment by wgao19** [comment]
thank you for this talk! (video is your own self edit and upload wo 😜)
