### ISSUE TITLE
 💠 Atomic Styling with Styled System

### ISSUE THREAD

**Issue by SheldonCheng** [react-knowledgeable/talks#42]
speaker
---
Sheldon, @sheldytox on Twitter

intro
---

With Styled System, you combine the best parts of Styled Components and atomic/utility styles! I'll talk about building layouts quickly using Styled System, then step back and touch on how it helps at a design system level.

resources
---

https://styled-system.com/

<details>
  <summary>planner</summary>

- I prefer to give this talk at: react-knowledgeable/events#6 
- Number of minutes needed to ⚡️: 10
- [x] I am happy to have this talk recorded by @engineersftw (by default, we record talks to be accessible by more audience, if you don't want, please uncheck this)

</details>

**Comment by wgao19** [comment]
hey @SheldonCheng is this more of a css talk?

**Comment by SheldonCheng** [comment]
Hey @wgao19 , it's more of a styled-components talk. Mark Dalgleish [talked abit](https://youtu.be/jnV1u67_yVg?t=426) about this at ReactiveConf recently. I've tweaked the talk name to be less confusing.

**Comment by wgao19** [comment]
closing because delivering at singaporecss, thank you still for preparing for this talk :)
