### ISSUE TITLE
🐈ワタシは猫ではない/i am a cat not

### ISSUE THREAD

**Issue by SmokinClove** [react-knowledgeable/talks#46]
speaker
---
Hello, i am Van, a member of the Web Front End team in Shopee.

intro
---

Besides Javascript, i also use 3 human languages everyday: Vietnamese, English and Japanese.
As these 3 languages have some interesting differences, i thought it'd be fun to use a few example sentences to compare them side by side. No, not Javascript. (Un)fortunately.

<details>
  <summary>planner</summary>

- I prefer to give this talk at: react-knowledgeable/events#82 
- Number of minutes needed to ⚡️: 7
- [x] I am happy to have this talk recorded by @engineersftw (by default, we record talks to be accessible by more audience, if you don't want, please uncheck this)

</details>

**Comment by wgao19** [comment]
Thanks for this sharing! [Here's link to video](https://youtu.be/ICBZLAPdgOo?t=299) :)
