### ISSUE TITLE
💨 Build and deploy a blog under 10 minutes with JAMstack

### ISSUE THREAD

**Issue by email2vimalraj** [react-knowledgeable/talks#5]
speaker profile
---
My name is Vimalraj Selvam. I am a Staff Software Engineer at Visa Worldwide Pte Ltd. I recently gave a talk in Berlin at GraphqlConf 2019 about Scaling GraphQL subscriptions. I build various visualisation tools using React for my company which is heavily used by the command center teams. I am mostly reachable via [twitter](https://twitter.com/email2vimalraj).

intro
---

I'd like to speak about **Build and deploy a blog under 10 minutes with JAMStack**. Here's a little more background and motivation about the talk:

JAMstack is hot now which enables anyone to build the websites with quick turnaround. During this talk, I'll show a quick demo on building a simple blog site and deploy it in netlify using Gatsby (React, GraphQL and markdowns).

As you can see above, I have a point to make. Please let me in thanks.

planner
---
- I prefer to give this talk at: August
- Number of minutes needed to ⚡️: 10

**Comment by wgao19** [comment]
Cool :) See you on Aug 6!
( Referencing #3 )

**Comment by wgao19** [comment]
Hi @email2vimalraj nice meeting you here! Could you please update your slides :))))) Thanks and hope to have you again!

Resources
---
- [video](https://engineers.sg/video/build-and-deploy-a-blog-under-10-minutes-with-jamstack-react-knowledge--3588)

**Comment by email2vimalraj** [comment]
Demo github repo: https://github.com/email2vimalraj/rk-meetup-talk-demo

[Slides](https://github.com/email2vimalraj/rk-meetup-talk-demo/blob/master/rk-meetup-presentation.key?raw=true)

**Comment by wgao19** [comment]
Great, thank you!
