### ISSUE TITLE
🍱 5 things you need to know about react-cache 

### ISSUE THREAD

**Issue by yishus** [react-knowledgeable/talks#6]
speaker profile
---
Yishu, does not like google forms. Spends waking hours at Carousell.

intro
---

`react-cache` is pretty exciting, let's share this excitement

planner
---
- I prefer to give this talk at: Aug
- Number of minutes needed to ⚡️: 7

**Comment by wgao19** [comment]
Thank you! So glad I won't miss this talk eventually :] See you Aug 6! #3

**Comment by wgao19** [comment]
Hi @yishus could you please update your slides here :]

- [video](https://engineers.sg/v/3587)
