### ISSUE TITLE
🖼 Image Compression on Javascript

### ISSUE THREAD

**Issue by Dlearn** [react-knowledgeable/talks#8]
## Speaker profile
---

My name is Dylan. I am interested in participating more in the Web dev community. I'm an atypicaly extroverted software engineer who loves speaking. I am mostly reachable via I have no idea, twitter? @dlaern or github?

## Intro
---

I'd like to speak about Image compression using pure javascript. Recently, we've implemented this during our migration project, and it was cool.

My initial implementation was copied from stackoverflow, but I found that the answer is slightly buggy, so I'm doing my part to reeducate the masses.

As you can see above, I have a point to make. Please let me in thanks.

## Planner
---
- I prefer to give this talk at: August
- Number of minutes needed to ⚡️: 10

**Comment by wgao19** [comment]
Great, you're on #3  :))))

**Comment by wgao19** [comment]
Hey @Dlearn could you please update your slides here :)))) thanks!

**Comment by wgao19** [comment]
[video](https://engineers.sg/video/image-compression-on-javascript-react-knowledgeable--3591)
